export const coffeeItems = [
  {
    id: "1",
    name: "Espresso",
    description: "Strong shot",
    price: "$2.50",
    rating: 4.8,
    image: require("../assets/images/3.png"),
  },
  {
    id: "2",
    name: "Latte",
    description: "Smooth milk",
    price: "$3.50",
    rating: 4.5,
    image: require("../assets/images/image.png"),
  },
  {
    id: "3",
    name: "Cappuccino",
    description: "Foamy top",
    price: "$3.00",
    rating: 4.6,
    image: require("../assets/images/image.png"),
  },
  {
    id: "4",
    name: "Mocha",
    description: "Choco blend",
    price: "$3.80",
    rating: 4.4,
    image: require("../assets/images/3.png"),
  },
  {
    id: "5",
    name: "Macchiato",
    description: "Bold mark",
    price: "$3.20",
    rating: 4.7,
    image: require("../assets/images/3.png"),
  },
  {
    id: "6",
    name: "Flat White",
    description: "Creamy shot",
    price: "$3.60",
    rating: 4.3,
    image: require("../assets/images/image.png"),
  },
];
